# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/larp/slonana-labs/limcode

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/larp/slonana-labs/limcode

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/larp/slonana-labs/limcode/CMakeFiles /home/larp/slonana-labs/limcode//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/larp/slonana-labs/limcode/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named limcode_ffi

# Build rule for target.
limcode_ffi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limcode_ffi
.PHONY : limcode_ffi

# fast build rule for target.
limcode_ffi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_ffi.dir/build.make CMakeFiles/limcode_ffi.dir/build
.PHONY : limcode_ffi/fast

#=============================================================================
# Target rules for targets named limcode_benchmark_ffi

# Build rule for target.
limcode_benchmark_ffi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limcode_benchmark_ffi
.PHONY : limcode_benchmark_ffi

# fast build rule for target.
limcode_benchmark_ffi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_benchmark_ffi.dir/build.make CMakeFiles/limcode_benchmark_ffi.dir/build
.PHONY : limcode_benchmark_ffi/fast

#=============================================================================
# Target rules for targets named limcode_snapshot

# Build rule for target.
limcode_snapshot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limcode_snapshot
.PHONY : limcode_snapshot

# fast build rule for target.
limcode_snapshot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_snapshot.dir/build.make CMakeFiles/limcode_snapshot.dir/build
.PHONY : limcode_snapshot/fast

#=============================================================================
# Target rules for targets named bench

# Build rule for target.
bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench
.PHONY : bench

# fast build rule for target.
bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/build
.PHONY : bench/fast

#=============================================================================
# Target rules for targets named benchmark_pure_cpp

# Build rule for target.
benchmark_pure_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_pure_cpp
.PHONY : benchmark_pure_cpp

# fast build rule for target.
benchmark_pure_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pure_cpp.dir/build.make CMakeFiles/benchmark_pure_cpp.dir/build
.PHONY : benchmark_pure_cpp/fast

#=============================================================================
# Target rules for targets named bench_theoretical_max

# Build rule for target.
bench_theoretical_max: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_theoretical_max
.PHONY : bench_theoretical_max

# fast build rule for target.
bench_theoretical_max/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_theoretical_max.dir/build.make CMakeFiles/bench_theoretical_max.dir/build
.PHONY : bench_theoretical_max/fast

#=============================================================================
# Target rules for targets named bench_true_maximum

# Build rule for target.
bench_true_maximum: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_true_maximum
.PHONY : bench_true_maximum

# fast build rule for target.
bench_true_maximum/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_true_maximum.dir/build.make CMakeFiles/bench_true_maximum.dir/build
.PHONY : bench_true_maximum/fast

#=============================================================================
# Target rules for targets named cpp_snapshot_test

# Build rule for target.
cpp_snapshot_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_snapshot_test
.PHONY : cpp_snapshot_test

# fast build rule for target.
cpp_snapshot_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_snapshot_test.dir/build.make CMakeFiles/cpp_snapshot_test.dir/build
.PHONY : cpp_snapshot_test/fast

#=============================================================================
# Target rules for targets named limcode_tests

# Build rule for target.
limcode_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limcode_tests
.PHONY : limcode_tests

# fast build rule for target.
limcode_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_tests.dir/build.make CMakeFiles/limcode_tests.dir/build
.PHONY : limcode_tests/fast

#=============================================================================
# Target rules for targets named cpp_bincode_compat

# Build rule for target.
cpp_bincode_compat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_bincode_compat
.PHONY : cpp_bincode_compat

# fast build rule for target.
cpp_bincode_compat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_bincode_compat.dir/build.make CMakeFiles/cpp_bincode_compat.dir/build
.PHONY : cpp_bincode_compat/fast

benchmark/bench.o: benchmark/bench.cpp.o
.PHONY : benchmark/bench.o

# target to build an object file
benchmark/bench.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmark/bench.cpp.o
.PHONY : benchmark/bench.cpp.o

benchmark/bench.i: benchmark/bench.cpp.i
.PHONY : benchmark/bench.i

# target to preprocess a source file
benchmark/bench.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmark/bench.cpp.i
.PHONY : benchmark/bench.cpp.i

benchmark/bench.s: benchmark/bench.cpp.s
.PHONY : benchmark/bench.s

# target to generate assembly for a file
benchmark/bench.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench.dir/build.make CMakeFiles/bench.dir/benchmark/bench.cpp.s
.PHONY : benchmark/bench.cpp.s

benchmark/bench_theoretical_max.o: benchmark/bench_theoretical_max.cpp.o
.PHONY : benchmark/bench_theoretical_max.o

# target to build an object file
benchmark/bench_theoretical_max.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_theoretical_max.dir/build.make CMakeFiles/bench_theoretical_max.dir/benchmark/bench_theoretical_max.cpp.o
.PHONY : benchmark/bench_theoretical_max.cpp.o

benchmark/bench_theoretical_max.i: benchmark/bench_theoretical_max.cpp.i
.PHONY : benchmark/bench_theoretical_max.i

# target to preprocess a source file
benchmark/bench_theoretical_max.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_theoretical_max.dir/build.make CMakeFiles/bench_theoretical_max.dir/benchmark/bench_theoretical_max.cpp.i
.PHONY : benchmark/bench_theoretical_max.cpp.i

benchmark/bench_theoretical_max.s: benchmark/bench_theoretical_max.cpp.s
.PHONY : benchmark/bench_theoretical_max.s

# target to generate assembly for a file
benchmark/bench_theoretical_max.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_theoretical_max.dir/build.make CMakeFiles/bench_theoretical_max.dir/benchmark/bench_theoretical_max.cpp.s
.PHONY : benchmark/bench_theoretical_max.cpp.s

benchmark/bench_true_maximum.o: benchmark/bench_true_maximum.cpp.o
.PHONY : benchmark/bench_true_maximum.o

# target to build an object file
benchmark/bench_true_maximum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_true_maximum.dir/build.make CMakeFiles/bench_true_maximum.dir/benchmark/bench_true_maximum.cpp.o
.PHONY : benchmark/bench_true_maximum.cpp.o

benchmark/bench_true_maximum.i: benchmark/bench_true_maximum.cpp.i
.PHONY : benchmark/bench_true_maximum.i

# target to preprocess a source file
benchmark/bench_true_maximum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_true_maximum.dir/build.make CMakeFiles/bench_true_maximum.dir/benchmark/bench_true_maximum.cpp.i
.PHONY : benchmark/bench_true_maximum.cpp.i

benchmark/bench_true_maximum.s: benchmark/bench_true_maximum.cpp.s
.PHONY : benchmark/bench_true_maximum.s

# target to generate assembly for a file
benchmark/bench_true_maximum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_true_maximum.dir/build.make CMakeFiles/bench_true_maximum.dir/benchmark/bench_true_maximum.cpp.s
.PHONY : benchmark/bench_true_maximum.cpp.s

benchmark/benchmark_pure_cpp.o: benchmark/benchmark_pure_cpp.cpp.o
.PHONY : benchmark/benchmark_pure_cpp.o

# target to build an object file
benchmark/benchmark_pure_cpp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pure_cpp.dir/build.make CMakeFiles/benchmark_pure_cpp.dir/benchmark/benchmark_pure_cpp.cpp.o
.PHONY : benchmark/benchmark_pure_cpp.cpp.o

benchmark/benchmark_pure_cpp.i: benchmark/benchmark_pure_cpp.cpp.i
.PHONY : benchmark/benchmark_pure_cpp.i

# target to preprocess a source file
benchmark/benchmark_pure_cpp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pure_cpp.dir/build.make CMakeFiles/benchmark_pure_cpp.dir/benchmark/benchmark_pure_cpp.cpp.i
.PHONY : benchmark/benchmark_pure_cpp.cpp.i

benchmark/benchmark_pure_cpp.s: benchmark/benchmark_pure_cpp.cpp.s
.PHONY : benchmark/benchmark_pure_cpp.s

# target to generate assembly for a file
benchmark/benchmark_pure_cpp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_pure_cpp.dir/build.make CMakeFiles/benchmark_pure_cpp.dir/benchmark/benchmark_pure_cpp.cpp.s
.PHONY : benchmark/benchmark_pure_cpp.cpp.s

benchmark/cpp_snapshot_test.o: benchmark/cpp_snapshot_test.cpp.o
.PHONY : benchmark/cpp_snapshot_test.o

# target to build an object file
benchmark/cpp_snapshot_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_snapshot_test.dir/build.make CMakeFiles/cpp_snapshot_test.dir/benchmark/cpp_snapshot_test.cpp.o
.PHONY : benchmark/cpp_snapshot_test.cpp.o

benchmark/cpp_snapshot_test.i: benchmark/cpp_snapshot_test.cpp.i
.PHONY : benchmark/cpp_snapshot_test.i

# target to preprocess a source file
benchmark/cpp_snapshot_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_snapshot_test.dir/build.make CMakeFiles/cpp_snapshot_test.dir/benchmark/cpp_snapshot_test.cpp.i
.PHONY : benchmark/cpp_snapshot_test.cpp.i

benchmark/cpp_snapshot_test.s: benchmark/cpp_snapshot_test.cpp.s
.PHONY : benchmark/cpp_snapshot_test.s

# target to generate assembly for a file
benchmark/cpp_snapshot_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_snapshot_test.dir/build.make CMakeFiles/cpp_snapshot_test.dir/benchmark/cpp_snapshot_test.cpp.s
.PHONY : benchmark/cpp_snapshot_test.cpp.s

src/limcode_benchmark_ffi.o: src/limcode_benchmark_ffi.cpp.o
.PHONY : src/limcode_benchmark_ffi.o

# target to build an object file
src/limcode_benchmark_ffi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_benchmark_ffi.dir/build.make CMakeFiles/limcode_benchmark_ffi.dir/src/limcode_benchmark_ffi.cpp.o
.PHONY : src/limcode_benchmark_ffi.cpp.o

src/limcode_benchmark_ffi.i: src/limcode_benchmark_ffi.cpp.i
.PHONY : src/limcode_benchmark_ffi.i

# target to preprocess a source file
src/limcode_benchmark_ffi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_benchmark_ffi.dir/build.make CMakeFiles/limcode_benchmark_ffi.dir/src/limcode_benchmark_ffi.cpp.i
.PHONY : src/limcode_benchmark_ffi.cpp.i

src/limcode_benchmark_ffi.s: src/limcode_benchmark_ffi.cpp.s
.PHONY : src/limcode_benchmark_ffi.s

# target to generate assembly for a file
src/limcode_benchmark_ffi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_benchmark_ffi.dir/build.make CMakeFiles/limcode_benchmark_ffi.dir/src/limcode_benchmark_ffi.cpp.s
.PHONY : src/limcode_benchmark_ffi.cpp.s

src/limcode_ffi.o: src/limcode_ffi.cpp.o
.PHONY : src/limcode_ffi.o

# target to build an object file
src/limcode_ffi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_ffi.dir/build.make CMakeFiles/limcode_ffi.dir/src/limcode_ffi.cpp.o
.PHONY : src/limcode_ffi.cpp.o

src/limcode_ffi.i: src/limcode_ffi.cpp.i
.PHONY : src/limcode_ffi.i

# target to preprocess a source file
src/limcode_ffi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_ffi.dir/build.make CMakeFiles/limcode_ffi.dir/src/limcode_ffi.cpp.i
.PHONY : src/limcode_ffi.cpp.i

src/limcode_ffi.s: src/limcode_ffi.cpp.s
.PHONY : src/limcode_ffi.s

# target to generate assembly for a file
src/limcode_ffi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_ffi.dir/build.make CMakeFiles/limcode_ffi.dir/src/limcode_ffi.cpp.s
.PHONY : src/limcode_ffi.cpp.s

src/snapshot.o: src/snapshot.cpp.o
.PHONY : src/snapshot.o

# target to build an object file
src/snapshot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_snapshot.dir/build.make CMakeFiles/limcode_snapshot.dir/src/snapshot.cpp.o
.PHONY : src/snapshot.cpp.o

src/snapshot.i: src/snapshot.cpp.i
.PHONY : src/snapshot.i

# target to preprocess a source file
src/snapshot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_snapshot.dir/build.make CMakeFiles/limcode_snapshot.dir/src/snapshot.cpp.i
.PHONY : src/snapshot.cpp.i

src/snapshot.s: src/snapshot.cpp.s
.PHONY : src/snapshot.s

# target to generate assembly for a file
src/snapshot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_snapshot.dir/build.make CMakeFiles/limcode_snapshot.dir/src/snapshot.cpp.s
.PHONY : src/snapshot.cpp.s

tests/cpp_bincode_compat.o: tests/cpp_bincode_compat.cpp.o
.PHONY : tests/cpp_bincode_compat.o

# target to build an object file
tests/cpp_bincode_compat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_bincode_compat.dir/build.make CMakeFiles/cpp_bincode_compat.dir/tests/cpp_bincode_compat.cpp.o
.PHONY : tests/cpp_bincode_compat.cpp.o

tests/cpp_bincode_compat.i: tests/cpp_bincode_compat.cpp.i
.PHONY : tests/cpp_bincode_compat.i

# target to preprocess a source file
tests/cpp_bincode_compat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_bincode_compat.dir/build.make CMakeFiles/cpp_bincode_compat.dir/tests/cpp_bincode_compat.cpp.i
.PHONY : tests/cpp_bincode_compat.cpp.i

tests/cpp_bincode_compat.s: tests/cpp_bincode_compat.cpp.s
.PHONY : tests/cpp_bincode_compat.s

# target to generate assembly for a file
tests/cpp_bincode_compat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_bincode_compat.dir/build.make CMakeFiles/cpp_bincode_compat.dir/tests/cpp_bincode_compat.cpp.s
.PHONY : tests/cpp_bincode_compat.cpp.s

tests/test_limcode.o: tests/test_limcode.cpp.o
.PHONY : tests/test_limcode.o

# target to build an object file
tests/test_limcode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_tests.dir/build.make CMakeFiles/limcode_tests.dir/tests/test_limcode.cpp.o
.PHONY : tests/test_limcode.cpp.o

tests/test_limcode.i: tests/test_limcode.cpp.i
.PHONY : tests/test_limcode.i

# target to preprocess a source file
tests/test_limcode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_tests.dir/build.make CMakeFiles/limcode_tests.dir/tests/test_limcode.cpp.i
.PHONY : tests/test_limcode.cpp.i

tests/test_limcode.s: tests/test_limcode.cpp.s
.PHONY : tests/test_limcode.s

# target to generate assembly for a file
tests/test_limcode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/limcode_tests.dir/build.make CMakeFiles/limcode_tests.dir/tests/test_limcode.cpp.s
.PHONY : tests/test_limcode.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bench"
	@echo "... bench_theoretical_max"
	@echo "... bench_true_maximum"
	@echo "... benchmark_pure_cpp"
	@echo "... cpp_bincode_compat"
	@echo "... cpp_snapshot_test"
	@echo "... limcode_benchmark_ffi"
	@echo "... limcode_ffi"
	@echo "... limcode_snapshot"
	@echo "... limcode_tests"
	@echo "... benchmark/bench.o"
	@echo "... benchmark/bench.i"
	@echo "... benchmark/bench.s"
	@echo "... benchmark/bench_theoretical_max.o"
	@echo "... benchmark/bench_theoretical_max.i"
	@echo "... benchmark/bench_theoretical_max.s"
	@echo "... benchmark/bench_true_maximum.o"
	@echo "... benchmark/bench_true_maximum.i"
	@echo "... benchmark/bench_true_maximum.s"
	@echo "... benchmark/benchmark_pure_cpp.o"
	@echo "... benchmark/benchmark_pure_cpp.i"
	@echo "... benchmark/benchmark_pure_cpp.s"
	@echo "... benchmark/cpp_snapshot_test.o"
	@echo "... benchmark/cpp_snapshot_test.i"
	@echo "... benchmark/cpp_snapshot_test.s"
	@echo "... src/limcode_benchmark_ffi.o"
	@echo "... src/limcode_benchmark_ffi.i"
	@echo "... src/limcode_benchmark_ffi.s"
	@echo "... src/limcode_ffi.o"
	@echo "... src/limcode_ffi.i"
	@echo "... src/limcode_ffi.s"
	@echo "... src/snapshot.o"
	@echo "... src/snapshot.i"
	@echo "... src/snapshot.s"
	@echo "... tests/cpp_bincode_compat.o"
	@echo "... tests/cpp_bincode_compat.i"
	@echo "... tests/cpp_bincode_compat.s"
	@echo "... tests/test_limcode.o"
	@echo "... tests/test_limcode.i"
	@echo "... tests/test_limcode.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

